<a href="https://colab.research.google.com/github/avinash-guntupalli/Neuralearn/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf

first_mat = tf.constant([[1,2,3],[2,3,4]])
second_mat = tf.constant([[4,5],[6,5],[4,7]])

tf.linalg.matmul(
    first_mat,second_mat,transpose_a = False, transpose_b = False,
    adjoint_a = False, adjoint_b = False,
    a_is_sparse=False, b_is_sparse= False, output_type=None, name=None
)



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[28, 36],
       [42, 53]], dtype=int32)>

In [6]:
# easy multplication

In [7]:
first_mat@second_mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[28, 36],
       [42, 53]], dtype=int32)>

In [8]:
tf.transpose(first_mat)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

In [11]:
# band part

band_mat = tf.constant([[2,3,4],[5,8,4],[8,6,9]])
tf.linalg.band_part(band_mat,0,0)

# 0 -1 upper traingle
# -1 0 lower triangle

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 0, 0],
       [0, 8, 0],
       [0, 0, 9]], dtype=int32)>

In [14]:

band_mat_type= tf.constant([[1,5,6],[3,6,7],[8.0,55,4]])




In [20]:
# singular value decomposition

# einsum

import numpy as np
mat_a = np.array([[2,6,5,2],
                 [2,-2,2,3],
                 [1,5,4,0]])
mat_b = np.array([[2,9,0,3,0],
                 [3,6,8,-2,2],
                 [1,3,5,0,1],
                 [3,0,2,0,5]])
print(mat_a.shape)
print(mat_b.shape)
print(np.matmul(mat_a,mat_b))

print("einsum")
print(np.einsum("ij,jk -> ik", mat_a,mat_b)) # easy to use

(3, 4)
(4, 5)
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]
einsum
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [24]:
mat_c = np.array([[1,5,7,8],[4,7,9,23],[7,4,6,44]])
print(np.einsum('ij,ij -> ij', mat_a,mat_c))

[[  2  30  35  16]
 [  8 -14  18  69]
 [  7  20  24   0]]


In [26]:
# einsum operation for matrix transpose

print(np.einsum('ij ->ji',mat_c))



[[ 1  4  7]
 [ 5  7  4]
 [ 7  9  6]
 [ 8 23 44]]
