<a href="https://colab.research.google.com/github/avinash-guntupalli/Neuralearn/blob/main/tensormath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf

x_abs = tf.constant([2.35,-8.9])
tf.abs(x_abs)


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.35, 8.9 ], dtype=float32)>

In [5]:
x_abs_complex = tf.constant([2+3j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([3.60555128])>

In [7]:
# tf add is the element wise addition

x_1 = tf.constant([5,3,6,6])
x_2 = tf.constant([3,4,5,6])
x_3 = tf.add(x_1,x_2)
print(x_3)

tf.Tensor([ 8  7 11 12], shape=(4,), dtype=int32)


In [8]:
x_4 = tf.constant([7])
print(tf.math.add(x_1,x_4))

tf.Tensor([12 10 13 13], shape=(4,), dtype=int32)


In [9]:
# mutiply

x_5 = [[5],[6],[7]]
print(tf.math.multiply(x_1,x_5))

tf.Tensor(
[[25 15 30 30]
 [30 18 36 36]
 [35 21 42 42]], shape=(3, 4), dtype=int32)


In [11]:
#arg max  => where the maximum value is

x = tf.constant([1,2,3,4])
print(tf.math.argmax(x))

tf.Tensor(3, shape=(), dtype=int64)


In [14]:
y = tf.constant([[1,2,3,4],[4,6,7,3],[8,9,33,7]])


print(tf.math.argmax(y,1))


# max value in each axis x-axis

tf.Tensor([3 2 2], shape=(3,), dtype=int64)


In [18]:
print(tf.math.reduce_sum(y,1))

tf.Tensor([10 20 57], shape=(3,), dtype=int32)
